// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPk4PHnLNAmNwL4a8qlArP7pcUJTpIBk',
    appId: '1:889239917779:web:36a1e9d26f57eef0b1f026',
    messagingSenderId: '889239917779',
    projectId: 'my-cool-final-project',
    authDomain: 'my-cool-final-project.firebaseapp.com',
    storageBucket: 'my-cool-final-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZKJuUlcnBZUjmswSjYlmwdOFcTB0i50',
    appId: '1:889239917779:android:5b89537f3f4f9808b1f026',
    messagingSenderId: '889239917779',
    projectId: 'my-cool-final-project',
    storageBucket: 'my-cool-final-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkUaRzTU9qA5Ok72eZwr5WEWtGf-0pdI',
    appId: '1:889239917779:ios:791b77f9fcf9edc2b1f026',
    messagingSenderId: '889239917779',
    projectId: 'my-cool-final-project',
    storageBucket: 'my-cool-final-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

}